language: node_js
dist: xenial
node_js:
  - "10"
git:
  depth: 5
  quiet: true
before_install:
  - rm -rf .git
  - npm set audit false
install:
  - git clone https://github.com/SukkaW/hexo-theme-suka themes/suka --depth=2
  - npm i > /dev/null
  - cd themes/suka
  - yarn install --production > /dev/null
  - cd ../..
  - \cp -f ./theme_config.yml themes/suka/_config.yml
script:
  - chmod +x ./perf-test.sh
  - ./perf-test.sh
cache:
  directories:
  - node_modules
  timeout: 60
