# ---------------------------------------------------------------
# !!ATTENTION!!
# There are some pivotal config which should be configured in site config!
# Read the documents for more info.
# ---------------------------------------------------------------

# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------
head:
  # Favicon
  #   Put your favicons into `hexo-site/source/` directory.
  #   To get or check favicons visit: https://realfavicongenerator.net
  favicon:
    # You should use a image/x-icon type icon and configure it here.
    ico: https://cdn.jsdelivr.net/gh/sukkaw/hexo-theme-suka@0.1.0/source/img/suka-favicon.ico
    # 16x16 png
    small: https://i1.wp.com/theme-suka.github.io/demo/img/suka-favicon.png?w=16
    # 32x32 png
    medium: https://i1.wp.com/theme-suka.github.io/demo/img/suka-favicon.png?w=32
    # 180x180 png
    apple_touch_icon: https://i1.wp.com/theme-suka.github.io/demo/img/suka-favicon.png?w=180
    # 192x192 png
    large: https://i1.wp.com/theme-suka.github.io/demo/img/suka-favicon.png?w=192
    # svg icon
    safari_pinned_tab:
  # Color
  #   It will defined color below:
  #     Android Chrome Color
  #     Safari Pinned Tab
  color:
  # PWA
  #   You can setup your blog as pwa with a manifest.
  #   https://app-manifest.firebaseapp.com where you can generate a manifest quickly
  #   Leave it blank if you don't have one
  pwa_manifest:
  # Microsoft Web App
  #   Windows 8 and 10 users can pin your web site on their desktop.
  #   Your site appears as a tile, just like a native Windows app.
  #   Leave it blank if you don't have one
  ms_browserconfig:
  # Open search
  #   Fill in your opensearch xml file here.
  #   Leave it blank if you don't have one
  open_search:
  # Keywords
  #   Define meta keywords tag
  #   split with ','
  keywords:
  # Site Verification
  site_verification:
    google:
    baidu:

footer:
  # Copyright Since
  # Specify the date when the site was setup.
  # For example, if you set it as 2015, then footer will show something like '© 2015 - 2018'
  # If you just want to show something like '© 2018' only, simly leave it blank.
  copyright_since: 2017
  # Footer Text
  # You can specify the text you want to show in footer, HTML tag is supported.
  # For example, you can setup ICP license number as:
  #   custom_text: '<a href="http://www.miitbeian.gov.cn" rel="nofollow noopener noreferrer">某ICP备xxxxxxxx号-x</a>'
  # Another example, you can setup 'Hosted on Coding Pages' as:
  #   custom_text: 'Hosted on <a href="https://pages.coding.me" rel="nofollow noopener noreferrer">Coding Pages</a>'
  # Muilt line footer text is supported.
  custom_text:
    - Hosted on <a href="https://pages.github.com/">GitHub Pages</a> & Cloudflare

# ---------------------------------------------------------------
# Customize Settings
# ---------------------------------------------------------------
uiux:
  # Muilt line slogan is supported.
  slogan: Hi, nice to meet you.
  # For most link color except post color
  link_color:
  primary_color:
  # Background color
  bg_color:

img:
  avatar: 'https://i1.wp.com/theme-suka.github.io/demo/img/default_avatar.png?w=24'

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------
# Nav settings
# Used to choose which
nav:
  home:
    use: true
  archives:
    use: true
  rss:
    use: false
  share:
    use: true
  search:
    use: true
    link: /demo/search/
  pages:
    Page:
      link: /demo/page/
    Links:
      link: /demo/links/
    Gallery:
      link: /demo/gallery/
    TagsCloud:
      link: /demo/tagscloud/

# SNS Share Switch
# Used to choose which items will be displayed in share menu.
sns_share:
  weibo: true
  facebook: true
  twitter: true
  telegram: true
  googleplus: true
  linkedin: true
  qq: true

# Qrcode which will show in share menu, for redirect to other device
qrcode:
  index_share: true
  post_share: true


# ---------------------------------------------------------------
# Post Settings
# ---------------------------------------------------------------
post:
  # Default Excerpt
  # Please use <!-- more --> in the post to control excerpt accurately and will override the configuration here.
  entry_excerpt: 120
  # Notify on expire of the page
  # To let the visitor know if the post hasn't been update for long.
  expire: true
  share: true
  # Post License
  # You can specify the text you want to show in the end of your posts and pages, HTML tag is supported.
  #   For example, you can setup a CC license as:
  #       license: 'This blog is under a <a href="/creativecommons.html" target="_blank">CC BY-NC-SA 3.0 Unported License</a>'
  # You can also use Front-Matter `license` to override this setting
  # or use Front-Matter `hide_license: true` to hide license on spefic post
  license: 'This demo is under a <a href="/creativecommons.html" target="_blank">CC BY-NC-SA 3.0 Unported License</a>'

# Table Of Contents which will be show on right side of the post
toc:
  # You can still disable toc for each single post by setting their front-matter with 'toc: false'
  enable: true
  # Show line number for each toc list-item or not. Default is true.
  line_number: true

# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------
# Comment Systems
# Available value of "use":
#     disqus | disqus_proxy | disqus_click | changyan | livere | gitment | gitalk | valine
# If you want to use gitment or gitalk,you should get the client_id and client_secret form https://github.com/settings/applications/new
# If you want to use valine,you should get the app_id and app_key form https://leancloud.cn , more setting please see https://valine.js.org
comment:
  use: disqusjs
  disqus:
    shortname: # disqus shortname
  disqusjs:
    shortname: theme-suka-demo
    siteName: Suka Theme Demo
    api: https://disqus.skk.moe/disqus/
    apikey: CjM0EUNSTrA3iZU13a11fgnGviL7KXVac0IF6XVl1ZgGPAC7qkCfGNbO4CnVBmap
    admin: SukkaW
    adminLabel: Admin
  changyan:
    appid:
    conf:
    thread_key_type: path # id | path. Only when you generate static id for each post before you using 'id'
  livere:
    data_uid:
  gitment:
    repo:
    owner:
    client_id:
    client_secret:
  gitalk:
    repo:
    owner:
    client_id:
    client_secret:
  valine:
    leancloud_appId:  # leancloud application app id
    leancloud_appKey:  # leancloud application app key
    notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
    verify: false # valine verify code (true/false)
    pageSize: 10 # comment list page size
    avatar: identicon # gravatar style https://valine.js.org/#/avatar
    lang: zh-cn # i18n
    placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
    guest_info: nick,mail,link #valine comment header info
  wildfire:
    database_provider: firebase # firebase or wilddog
    wilddog_site_id:
    firebase_api_key:
    firebase_auth_domain:
    firebase_database_url:
    firebase_project_id:
    firebase_storage_bucket:
    firebase_messaging_sender_id:
    theme: light # light or dark
    locale: en # en or zh-CN

# Site Analytics
# Material theme has a built in Baidu's, Google's website analytics and CNZZ's analytics service
analytics:
  google_site_id:
  gtags_site_id:
  baidu_site_id:
  cnzz_site_id:

# Views Analytics
# The counter by https://busuanzi.ibruce.info
busuanzi:
  enable: true
  # Site views analytics support either pv or uv
  # will be show at footer
  site_uv:
    enable: true
    before: # html tag support
    after: Viewers # html tag support
    divider: '|' # html tag supported, something like '|' ',' '·' even '<br>', if you dont want any divider simply leave it blank,
    offset: 10
  site_pv:
    enable: false
    before: # html tag support
    after: Views # html tag support
    divider: # html tag supported, something like '|' ',' '·' even '<br>', if you dont want any divider simply leave it blank,
    offset: 0
  # Post views analytics
  # will be show at post header info
  post_pv:
    enable: true
    before: # html tag support
    after: Views # html tag support

# The counter by https://valine.js.org/visitor.html
valine_counter:
  # ATTENTION! You should use valine comment system to enable this feature!
  enable: false
  # By use config.url as id to count all site pv
  site_pv:
    enable: false
    before: # html tag supported
    after: # html tag supported
    divider: # html tag supported, something like '|' ',' '·' even '<br>', if you dont want any divider simply leave it blank,
  # Show pv for every post on index (Exprimental)
  index_post_pv:
    enable: false
    before: # html tag supported
    after: # html tag supported
  # Show pv on post page
  post_pv:
    enable: false
    before: # html tag supported
    after: # html tag supported

# Search
# Available value of "use":
#     local | google | swiftype
search:
  use: local
  # Swiftype
  swiftype_key:

# Code highlight
# You can only enable one of them to avoid issues.
# Also you need to disable all highlight option in hexo's site config.
#   highlight:
#     enable: false
#     line_number: false
#     auto_detect: false
#     tab_replace: false
#
# Suka Theme has built in those code highlight: Prism | Hanabi | Prettify
# Run `hexo clean` first after changing code highlight configuration.

# Hanabi (https://github.com/egoist/hanabi)
hanabi:
  enable: false

# Prism
# Disable other code hightlight first and enable prism at site config:
#    suka_theme:
#      ...
#      prism:
#        enable: true

# Google Code Prettify
prettify:
  enable: false
  linenumber: true # We prefer to enable for avoiding some pretiffy's bugs.
  # Prettify Theme
  theme: github-v2 # It will not load any theme if you leave it blank
  # You can only enable the Suka built in prettify theme here. Check the /source/lib/prettify/themes directories.
  # The theme name is the css file name without `.min.css`, as [theme-name].min.css
  #
  # If you want to use other theme, you can leave that blank, and load your own theme by adding <link> tag using custom code.
  # Learn how to use custom code here: https://theme-suka.github.io/docs/en/expert/#Add-custom-code

# ---------------------------------------------------------------
# Expert Settings
# ---------------------------------------------------------------
# !!ATTENTION!!
# Do Not Modify Below This Line, unless you know what you are doing!
# ---------------------------------------------------------------

# Vendors
#   Set a CDN address for the vendor you want to customize.
#   Be aware that you should use the same version as internal ones to avoid potential problems.
#   We prefer you using the https protocol of CDN files whether you enable https on your site or not.
vendors:
  # hexo-theme-suka
  # https://github.com/SukkaW/hexo-theme-suka
  suka:
    style_css: 
    local_search_js: https://cdn.jsdelivr.net/gh/sukkaw/hexo-theme-suka@1.2.0/source/js/local-search.min.js
    lazyload_img: 'data:image/gif;base64,R0lGODlhAQABAID/AP///wAAACwAAAAAAQABAAACAkQBADs='
    hanabi_browser_js:
    highlight_theme: https://cdn.jsdelivr.net/gh/sukkaw/hexo-theme-suka@1.2.0/source/css/highlight/github.min.css
    gallery_css:
    gallery_js:
  # Spectre.css
  # https://picturepan2.github.io/spectre/
  # Version: 0.5.3
  spectre:
    spectre_css: https://cdn.jsdelivr.net/npm/spectre.css@0.5.3
  # Prism & Prism Theme
  # https://github.com/PrismJS/prism/ https://github.com/PrismJS/prism-themes
  # Prism Version: 1.15.0 | Prism Theme Version: 1.0.1
  prism:
    theme: https://cdn.jsdelivr.net/gh/sukkaw/hexo-theme-suka@0.1.0/source/lib/prism/prism-default.min.css
    line_number: https://cdn.jsdelivr.net/gh/sukkaw/hexo-theme-suka@0.1.0/source/lib/prism/prism-line-numbers.min.css
  # Lazyload
  # https://github.com/verlok/lazyload
  # Version: 8.9.0
  lazyload: https://cdn.jsdelivr.net/npm/vanilla-lazyload@8.9.0
  # Busuanzi
  # https://busuanzi.ibruce.info
  busuanzi: https://cdn.jsdelivr.net/npm/busuanzi@2.3.0
  # Hanabi
  # https://github.com/egoist/hanabi
  hanabi: https://cdn.jsdelivr.net/npm/hanabi@0.4.0/dist/hanabi.min.js
  # Prettify Core
  # Attention! It is NOT the `run_prettify.js`!
  # Version: 0.1.0
  prettify:
  # Prettify Theme
  # You can fill in any prettify theme you want here, and it will also override the prettify theme config below.
  # Personally I prefer the theme here: https://github.com/jmblog/color-themes-for-google-code-prettify
  prettify_theme: https://cdn.jsdelivr.net/npm/color-themes-for-google-code-prettify@2.0.4/dist/themes/github-v2.min.css

fragment_cache: true
# Theme Version
#   localStorage cache version
verison: 1.0.1
old_verison:
  - 0.2.0
  - 0.0.1
  - 0.1.0
  - 1.0.0